<?php
function local_layout_styles_layout_alter(&$definitions) {
  //kint($definitions);
  // Remove the default layouts to unclutter things.
  //unset($definitions['twocol']);
  //unset($definitions['layout_twocol_section']);
  //unset($definitions['layout_threecol_section']);
  //unset($definitions['layout_onecol']);
  //unset($definitions['layout_twocol_bricks']);
  //unset($definitions['layout_threecol_25_50_25']);
  //unset($definitions['layout_threecol_33_34_33']);
  //unset($definitions['layout_onecol_section']);
  //unset($definitions['layout_fourcol_section']);

  #Needs to be there or d no likey!!!
  //unset($definitions['layout_builder_blank']);
}